M48
; DRILL file KiCad 10.0.4 date 2026-07-18T16:01:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-18T16:01:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X252.025Y-147.357
X252.025Y-150.357
T2
X160.0Y-108.533
X172.5Y-152.0
X234.937Y-154.663
M30
