meta:
  engine: 4.1.0
  name: ergogenesis
  version: 1.2
  author: Imochoa
  url: https://github.com/imochoa
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # For the web preview on ergogen.ceoloide
  $default_width: 1cx
  $default_height: 1cy
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        # Fix placement on KiCAD sheet.
        shift: [150, -150]
        # rotate: 15
      columns:
        pinky:
        ring:
          key.splay: -5
          key.origin: [-12, -19]
          key.stagger: 12
        middle:
          key.stagger: 5
        index:
          key.stagger: -6
        inner:
          key.stagger: -2
      rows:
        bottom:
        home:
        top:
    thumbfan:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        # near:
        home:
          key.spread: 21.25
          key.splay: -28
          key.origin: [-11.75, -9]
        far:
          key.spread: 21.25
          key.splay: -28
          key.origin: [-9.5, -9]
      rows:
        thumb:
outlines:
  # outline of all keys
  raw:
    - what: rectangle
      where: true
      # asym: source
      size: [px, py]
  # To look for potential overlaps between keys
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px,+0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,+0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,+0.5py]
        - ref: matrix_middle_top
          shift: [+0.5px,+0.5py]
        - ref: matrix_inner_top
          shift: [+0.5px,+0.5py]
        - ref: thumbfan_far_thumb
          shift: [+0.5px,+0.5py]
        - ref: thumbfan_far_thumb
          shift: [+0.5px,-0.5py]
        - ref: thumbfan_home_thumb
          shift: [-0.5px,-0.5py]
  # to see if it all fits  
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  tutorial:
    outlines:
      main:
        outline: board
    footprints:
      # arbitrary name
      choc_hotswap:
        # https://github.com/ergogen/ergogen/tree/develop/src/footprints
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: false # through-hole
          from: "{{column_net}}"
          to: "{{colrow}}"
      # any name
      promicro:
        # https://github.com/ergogen/ergogen/blob/develop/src/footprints/promicro.js
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          shift: [0,0]
          rotate: 0
      # name
      reset:
        what: button
        params:
          from: GND
          to: RST
