# this file MUST be named config.yaml
# online editor: https://ergogen.ceoloide.com
meta:
  engine: 4.1.0
  name: ergogenesis
  version: 1.2
  author: Imochoa
  url: https://github.com/imochoa
units:
  # Proxy Spacing Variables
  # NOTE: cx and cy are the default choc keycap sizes: 18mm wide and 17mm tall
  # MBK keys are SMALLER???
  kx: cx
  ky: cy
  # U: 19.05mm MX spacing
  # u: 19mm MX spacing
  # cx: 18mm Choc X spacing
  # cy: 17mm Choc Y spacing
  # For the web preview on ergogen.ceoloide
  $default_width: 18
  $default_height: 17
  # Padding Variables
  px: kx + 4
  py: ky + 4
points:
  zones:
    grid-zn:
      anchor:
        # Fix placement on KiCAD sheet.
        shift: [150, -150]
        # rotate: 15
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key:
            # col_net: P7
          rows:
            bottom:
            home:
              shift: [-2, 0]
            top:
              shift: [-2, 0]
        ring:
          key:
            # splay: -5
            # origin: [-12, -19]
            stagger: 12.573
          rows:
            bottom:
              # splay: -50
            home:
              shift: [-1, 0]
            top:
              shift: [-1, 0]
        middle:
          key:
            # splay:
            stagger: +4.763
        index:
          key:
            # splay:
            stagger: -4.763
          rows:
            bottom:
              # splay: -50
            home:
              shift: [+0, 0]
            top:
              shift: [+0, 0]
        inner:
          key:
            stagger: -2.86
          rows:
            bottom:
              # splay: -50
            home:
              shift: [+0, 0]
            top:
              shift: [+0, 0]
      rows:
        bottom:
        home:
        top:
    thumb-zn:
      # key:
      #   padding: 1ky
      #   spread: 1kx
      anchor:
        ref: grid-zn_index_bottom
        # shift: [12.573, -23.81]
        shift: [8, -20]
        rotate: -9
      columns:
        near:
        home:
          key:
            # spread: 20
            splay: -20
            origin: [-10, -6]
        far:
          key:
            # spread: 19
            splay: -20
            origin: [-10, -6]
      rows:
        thumb:
outlines:
  # outline of all keys
  raw-ol:
    - what: rectangle
      where: true
      # asym: source
      size: [px, py]
  # To look for potential overlaps between keys
  keys-ol:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board-ol:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        # Bottom Left (pinky)
        - ref: grid-zn_pinky_bottom
          shift: [-0.5px -4, -0.5py]
        - ref: grid-zn_pinky_top
          shift: [-0.5px, +0.5py]
        - ref: grid-zn_ring_top
          shift: [-0.5px, +0.5py]
        - ref: grid-zn_middle_top
          shift: [-0.5px, +0.5py]
        - ref: grid-zn_middle_top
          shift: [+0.5px, +0.5py]
        - ref: grid-zn_inner_top
          shift: [+0.5px, +0.5py]
          # MCU
        - ref: grid-zn_inner_top
          shift: [+0.5px, -0.0py]
        - ref: grid-zn_inner_top
          shift: [+0.5px +18, +0.0py]
          # Transition to thumb
        - ref: grid-zn_inner_bottom
          shift: [+0.5px +18, -0.5py]
          # Thumb cluster
        - ref: thumb-zn_far_thumb
          shift: [+0.5px, +0.5py]
        - ref: thumb-zn_far_thumb
          shift: [+0.5px, -0.5py]
        - ref: thumb-zn_home_thumb
          shift: [-0.5px, -0.5py]
          # 90 degree clamp
  # to see if it all fits
  combo-ol:
    - name: board-ol
    - operation: subtract
      name: keys-ol
cases:
  ergogenesis:
    - what: outline
      name: board-ol
      extrude: 3

pcbs:
  shield-pcb:
    outlines:
      main:
        outline: board-ol

    footprints:
      key-fp:
        # https://github.com/ergogen/ergogen/blob/develop/src/footprints/choc.js
        what: choc
        where: true # all keys
        params:
          keycaps: false # do I want it drawn on the PCB? They are not the right size!
          reverse: true
          hotswap: false
          from: GND
          to: "{{name}}"

      mcu-fp:
        # https://github.com/ergogen/ergogen/blob/develop/src/footprints/promicro.js
        # what: promicro
        # ./footprints/promicro-pretty.js
        what: promicro-pretty
        where:
          ref: grid-zn_inner_top
          shift: [+19.05, -17]
          # rotate: 0
        params:
          # for ergogen fp
          # orientation: "down" # power led will face the pcb
          # ./footprints/promicro-pretty.js
          reversable: true
          reversable_pins: 13 # 13a; all of them!
          label: true
          instructions: true
          traces: true
          view: true
          # only_required_jumpers: true
          # P0-P10
          # P14-P16
          # P18-P21
          P7: grid-zn_pinky_top
          P18: grid-zn_ring_top
          P19: grid-zn_middle_top
          P20: grid-zn_index_top
          P21: grid-zn_inner_top
          # home
          P15: grid-zn_pinky_home
          P14: grid-zn_ring_home
          P16: grid-zn_middle_home
          P10: grid-zn_index_home
          P1: grid-zn_inner_home
          # bottom
          P2: grid-zn_pinky_bottom
          P3: grid-zn_ring_bottom
          P4: grid-zn_middle_bottom
          P5: grid-zn_index_bottom
          P6: grid-zn_inner_bottom
          # thumb
          P8: thumb-zn_home_thumb
          P9: thumb-zn_far_thumb
          # from me...
          P0: thumb-zn_near_thumb
          # Others...
          # RAW:
          # BAP
          # RST
          # VCC
          # GND
      # reset-fp:
      #   # https://github.com/ergogen/ergogen/blob/develop/src/footprints/button.js
      #   what: button
      #   params:
      #     from: GND
      #     to: RST
      battery-connector-fp:
        # ./footprints/jstkss2b-ph-kl.js
        # TODO: is this the same as https://github.com/MvEerd/ergogen/blob/mountinghole/src/footprints/jstph.js
        what: jst-s2b-ph-kl
        where:
          ref:
            - grid-zn_inner_bottom
          # pointing to MCU
          rotate: 180
          shift: [20, -13]
          # # aligned with thumb
          # shift: [30, -20]
          # rotate: +230
        params:
          neg: B-
          pos: pos
      on-off-switch-fp:
        # ./footprints/pcm12.js
        what: pcm12
        where:
          ref:
            - grid-zn_inner_bottom
          # shift: [32, 3]
          # rotate: 90
          # # aligned with thumb
          shift: [28, -20]
          rotate: 125
        params:
          from: pos
          to: B+
      front-text-fp:
        # ./footprints/text.js
        what: text
        where:
          ref:
            - grid-zn_pinky_bottom
          shift: [12, -7]
        params:
          text: No me saques sin razón...
          # layer: F.SilkS
          justify: left
          h_size: 3
          v_size: 3 # should be same as h_size
          # thickness: 0.15,
          # style: italic
          # Expecting 'face, size, line_spacing, thickness, bold, or italic' in '/var/folders/cp/
      back-text-fp:
        # ./footprints/text.js
        what: text
        where:
          ref:
            - grid-zn_pinky_bottom
          shift: [27, -7]
        params:
          text: ...ni me envaines sin honor
          layer: B.SilkS
          justify: left mirror

      image-fp:
        # ./footprints/image.js
        what: image
        where:
          ref: grid-zn_middle_bottom
          shift: [-5, -15]

      # screws-fp:
      #   what: mounting_hole
      #   params:
      #   where: [screw]
