set positional-arguments := true
set shell := ["bash", "-euco", "pipefail"]

build := absolute_path('.build')
result := absolute_path('result')
draw := absolute_path('draw')
home_dir := env('HOME')

# Open picker with "jj" alias
[no-cd]
_default:
    @just --list --list-submodules

[group('ergogen')]
setup:
    pnpm import
    pnpm install

[group('ergogen')]
ergogen-build:
    pnpm run ergogen:build

[group('ergogen')]
ergogen-watch:
    pnpm run ergogen:watch

[group('ergogen')]
ergogen-stl-from-jscad:
    fd -ejscad . . -x npx @jscad/cli@1 "{}" -of stla -o "{.}.stl"

# [group('ergogen')]

# visualize-dxf dxf-file="./ergogen/output/outlines/combo_ol.dxf":
visualize-dxf dxf-file="./ergogen/output/outlines/stack_ol.dxf":
    # uv tool run 'ezdxf[draw]' view "{{ dxf-file }}"
    # uv tool run "ezdxf[draw]" view  ./ergogen/output/outlines/combo_ol.dxf
    # watchexec -e dxf -w ./ergogen/output/outlines -- uv tool run 'ezdxf[draw]' view "{{ dxf-file }}"
    watchexec -r -w ./output/outlines 'uv tool run "ezdxf[draw]" view "{{ dxf-file }}"'

output-dir := "{{justfile_dir()}}/output"
kicad-pcb := "shield-pcb"

[group('kicad')]
kicad-checks:
    kicad-cli pcb drc ./output/pcbs/shield-pcb.kicad_pcb
    # kicad-cli sch check ergogen/schematic/ergogenesis.kicad_sch
    # kicad-cli pcb check ergogen/output/pcb/ergogenesis.kicad_pc

[group('kicad')]
kicad-freerouting-gui:
    # nix-shell -p freerouting --run 'freerouting'
    nix shell nixpkgs#freerouting \
        --command freerouting \
        -da \
        -de "./manual/shield-pcb.dsn" \
        -do "./manual/shield-pcb-routed.ses" \
        -di "./manual/" \
        -inc GND \
        -mt 1 \
        --router.optimizer.max_threads=0

# other cli args: https://github.com/freerouting/freerouting/blob/master/docs/command_line_arguments.md
#  --gui.enabled=false
# other settings: https://github.com/freerouting/freerouting/blob/master/docs/settings.md
# has api server! use from Kicad?

[group('kicad')]
kicad-export-3d format="step":
    # Export the populated PCB (board + all 3D component models) to a 3D
    # format. `format` is one of: step, stl, glb, vrml, ply, u3d, brep, xao.
    # The ERGOGEN_3DMODELS variable resolves the ${...} paths in the footprints.
    kicad-cli pcb export {{ format }} \
        -o ./output/pcbs/shield-pcb.{{ format }} \
        -D ERGOGEN_3DMODELS="{{ justfile_dir() }}/3dmodels" \
        --force \
        ./output/pcbs/shield-pcb.kicad_pcb

[group('kicad')]
kicad-export-pdf:
    # front
    kicad-cli pcb export pdf \
        -l F.Cu,F.Adhesive,F.Paste,F.Silkscreen,F.Mask,F.Courtyard,F.Fab,Edge.Cuts \
        --output pcb-FRONT.pdf \
        --black-and-white \
        --include-border-title \
        ./ergogen/output/pcbs/shield-pcb.kicad_pcb
    # back
    kicad-cli pcb export pdf \
        -l B.Cu,B.Adhesive,B.Paste,B.Silkscreen,B.Mask,B.Courtyard,B.Fab,Edge.Cuts \
        --output pcb-BACK.pdf \
        --black-and-white \
        --include-border-title \
        ./ergogen/output/pcbs/shield-pcb.kicad_pcb

[group('ci')]
just-check:
    just --fmt --check --unstable

[group('ci')]
just-fmt:
    just --fmt --unstable
